//Click
if(Tool==0)
{
  diagConfirm.tPrompt.txt="Switch to Extruder 2?"
  ReturnVal=1
}else
{
  diagConfirm.tPrompt.txt="Switch to Extruder 1?"
  ReturnVal=0
}
ReturnObj=20
ReturnPage=dp
page diagConfirm

//Do callback
if(HandleCallback==1)
{
  vars.debug.txt="Doing Callback for "
  covx ReturnObj,vars.s.txt,0,0
  vars.debug.txt+=vars.s.txt
  click ReturnObj,0 //Right click
}
HandleCallback=0
ReturnVal=0