///////////////////////////////////////////////////////////////////////////////
/// @fn luxController,1
/// @brief Custom callback
///////////////////////////////////////////////////////////////////////////////
// Intentionally Blank

///////////////////////////////////////////////////////////////////////////////
/// @fn luxController,0
/// @brief Custom callback
///////////////////////////////////////////////////////////////////////////////
click setIdexMode,1

///////////////////////////////////////////////////////////////////////////////
/// @fn luxView,1
/// @brief Updates states for controls
///////////////////////////////////////////////////////////////////////////////
if(IdexMode==0)
{
  bManual.picc=bManual.picc2
}
if(IdexMode==1)
{
  bAuto.picc=bAuto.picc2
}
if(IdexMode==2)
{
  bClone.picc=bClone.picc2
}
if(IdexMode==3)
{
  bMirror.picc=bMirror.picc2
}


///////////////////////////////////////////////////////////////////////////////
/// @fn setIdexMode
/// @breif Set idex mode from a return value
///////////////////////////////////////////////////////////////////////////////
commands.command.txt="G28 X\r"
commands.command.txt+="M605 S"
covx ReturnVal,vars.s.txt,0,0
commands.command.txt+=vars.s.txt
commands.command.txt+="\r"
click luxSend,1
IdexMode=ReturnVal

//Buttons
//Manual
if(IdexMode!=0)
{
  diagPrompt.tMessage.txt="Switch to Manual Mode?"
  DiagReturnPage=dp
  ReturnObj=0
  ReturnVal=0
  page diagPrompt
}

//Auto
if(IdexMode!=1)
{
  diagPrompt.tMessage.txt="Switch to Auto Mode?"
  DiagReturnPage=dp
  ReturnObj=0
  ReturnVal=1
  page diagPrompt
}

//Clone
if(IdexMode!=2)
{
  diagPrompt.tMessage.txt="Switch to Clone Mode?"
  DiagReturnPage=dp
  ReturnObj=0
  ReturnVal=2
  page diagPrompt
}

//Mirror
if(IdexMode!=3)
{
  diagPrompt.tMessage.txt="Switch to Mirror Mode?"
  DiagReturnPage=dp
  ReturnObj=0
  ReturnVal=3
  page diagPrompt
}


