//Page load
prints "G28",0 //Home
printh 0A
prints "M114",0 //Report position
printh 0A

ReturnPage=dp
//Do callback
if(HandleCallback==1)
{
  click ReturnObj,0 //Mouse up
  HandleCallback=0
  ReturnVal=-1
}


//bSwap callback
vars.status.txt="Swapping Tool"
if(ReturnVal!=-1)
{
  prints "T",0
  covx ReturnVal,vars.s.txt,0,0
  prints vars.s.txt,0
  printh 0A
}

//updateState
if(Tool==0)
{
  bSwap.picc=14
}else
{
  bSwap.picc=15
}



