///////////////////////////////////////////////////////////////////////////////
/// @fn luxRunOnce
/// @breif Does not run when returning from dialog boxes
///////////////////////////////////////////////////////////////////////////////
commands.command.txt="G28\r" //Home
commands.command.txt+="M605 S1\r" //Set to auto mode
commands.command.txt+="T0\r"
commands.command.txt+="G0 F5000\r"
commands.command.txt+="M114\r" //Report position
click luxSend,1

///////////////////////////////////////////////////////////////////////////////
/// @fn luxInitialize 0
/// @brief Should run on any close button
///////////////////////////////////////////////////////////////////////////////
commands.command.txt="G28\r" //Home
commands.command.txt+="T0\r" //Set to T0
commands.command.txt+="G0 F5000\r"
click luxSend,1
page ReturnPage

///////////////////////////////////////////////////////////////////////////////
/// @fn luxView,1
/// @brief Updates states for controls
///////////////////////////////////////////////////////////////////////////////
bSwap.picc=bSwap.picc2+1
bSwap.picc+=Tool
tPosition.txt="X:"
tPosition.txt+=printer.x.txt
tPosition.txt+=" "
tPosition.txt+="Y:"
tPosition.txt+=printer.y.txt
tPosition.txt+=" "
tPosition.txt+="Z:"
tPosition.txt+=printer.z.txt

///////////////////////////////////////////////////////////////////////////////
/// @fn sendCommand
/// @brief Prepare and send commands
///////////////////////////////////////////////////////////////////////////////
commands.command.txt="G90\r"
commands.command.txt+="G0 Z10 F400\r"
commands.command.txt+="G0 X"
covx destX.val,vars.s.txt,0,0
commands.command.txt+=vars.s.txt
commands.command.txt+=" Y"
covx destY.val,vars.s.txt,0,0
commands.command.txt+=vars.s.txt
commands.command.txt+=" F5000\r"
commands.command.txt+="G0 Z0 F400\r"
commands.command.txt+="M114\r"
click luxSend,1

///////////////////////////////////////////////////////////////////////////////
//bPoint1
destX.val=50
destY.val=50
click sendCommand,1

//bPoint2
destX.val=250
destY.val=250
click sendCommand,1

//bPoint3
destX.val=250
destY.val=50
click sendCommand,1

//bPoint4
destX.val=50
destY.val=250
click sendCommand,1

//bPoint5
destX.val=150
destY.val=150
click sendCommand,1