//Onload
click updateState,1
ReturnPage=dp
DiagReturnPage=dp
if(HandleCallback==1)
{
  click b[ReturnObj],0 //Run right click code as callback
  HandleCallback=0
  vars.returnVal.txt="null"
  ReturnVal=-1
}

//Route
// Direct to print page
parse.lineMatch.txt="SD printing byte " //Qualify Line
strlen parse.lineMatch.txt,j
substr parse.buffer.txt,parse.eval.txt,0,j
if(parse.eval.txt==parse.lineMatch.txt)
{
  page print
}