// Serial Parser
int MAIN=5,PIC_CLEAR=0,SLEEP_TIME=900 //15 minutes
int BlockCount=0,State=0 //depreciated
int Baud=0,SerialPos=0,BufferLen=0,SearchPos=0,ok=1,busy=0,QueueBlocks=0,MaxQueueBlocks=10,OkBlocks=0,MaxOKBlocks=50
int ReturnPage=4,DiagReturnPage,ReturnObj=-1,ReturnVal=-1,HandleCallback=0
int Frame=0,FrameB=0
int Tool=0,IdexMode=1
int j=0,k=0,l=0,c=0
baud=0
recmod=1
thsp=SLEEP_TIME //Sleep time
thup=1 //Wake on Touch
wup=255
page connect
page print
